runtime: go116

env: standard
app_engine_apis: true
instance_class: F1
handlers:
  - url: /queue/.*
    script: auto
    login: admin

  - url: '/.*'
    script: auto

env_variables:
  ESUN: "https://www.esunbank.com.tw/bank/personal/deposit/rate/forex/foreign-exchange-rates"
  SELECTION: "#exchangeRate table tbody tr.JPY td:nth-child(11)"
  TO: <to@mail>
