runtime: go
api_version: go1

env: standard
threadsafe: false
instance_class: F1
handlers:
  - url: /queue/.*
    script: _go_app
    login: admin

  - url: '/.*'
    script: _go_app

env_variables:
  ESUN: "https://www.esunbank.com.tw/bank/personal/deposit/rate/forex/foreign-exchange-rates"
  SELECTION: "#inteTable1 tbody tr:nth-child(6)"
  EXPECTED: "0.2705"
  TO: <to@mail>
